/**
 * NewRoutineCard - Inline wizard for creating new routines
 *
 * Per unified-scheduler-mockup.html, displays an expanded card with:
 * - TriggerSelector for type and configuration
 * - ActionList for adding actions
 * - Save/Cancel buttons
 *
 * @module components/scheduler/ScheduleEditor/NewRoutineCard
 */

import { useState, useCallback, memo } from 'react'
import toast from 'react-hot-toast'
import TriggerForm from './TriggerForm'
import PreConditionForm from './PreConditionForm'
import ActionList from './ActionList'
import { TRIGGER_DEFAULTS } from './constants'
// @ts-expect-error -- .js module
import { generateUUID } from '@/utils/uuid'
import { intervalTriggerSchema } from '@/schemas/scheduler/interval'
import { solarTriggerSchema } from '@/schemas/scheduler/solar'
import { moonPhaseTriggerSchema } from '@/schemas/scheduler/moon-phase'
import { fixedTimeTriggerSchema } from '@/schemas/scheduler/fixed-time'
import { sensorTriggerSchema } from '@/schemas/scheduler/sensor'
import { recurringDaysTriggerSchema } from '@/schemas/scheduler/recurring-days'
import { cronExpressionSchema } from '@/schemas/scheduler/cron'
import type { Routine, Trigger, RoutineAction, PreCondition } from './scheduler-types'

/**
 * Validate a trigger using the appropriate Zod schema for its type.
 * Returns a human-readable error string, or null if valid.
 */
function validateTriggerWithSchema(trigger: Trigger): string | null {
  const schemas: Record<string, import('zod').ZodTypeAny> = {
    interval: intervalTriggerSchema,
    solar: solarTriggerSchema,
    moon_phase: moonPhaseTriggerSchema,
    fixed_time: fixedTimeTriggerSchema,
    sensor: sensorTriggerSchema,
    recurring_days: recurringDaysTriggerSchema,
    cron: cronExpressionSchema,
  }

  const schema = schemas[trigger.trigger_type]
  if (!schema) return null // unknown type passes (server validates)

  const result = schema.safeParse(trigger)
  if (result.success) return null

  // Return the first error message
  return result.error.issues[0]?.message ?? 'Invalid trigger configuration'
}

interface NewRoutineCardProps {
  /** Callback when routine is saved */
  onComplete: (routine: Routine) => void;
  /** Callback when creation is cancelled */
  onCancel: () => void;
  /** Whether form is disabled */
  disabled?: boolean;
  /** Whether to show explicit seconds timing vs auto-stagger */
  useSecondsTiming?: boolean;
}

/**
 * NewRoutineCard component
 *
 * @example
 * <NewRoutineCard
 *   onComplete={(routine) => console.log('created', routine)}
 *   onCancel={() => console.log('cancelled')}
 * />
 */
function NewRoutineCard({ onComplete, onCancel, disabled = false, useSecondsTiming = false }: NewRoutineCardProps) {
  // Initialize with default interval trigger
  const [trigger, setTrigger] = useState<Trigger>(() => ({ ...TRIGGER_DEFAULTS.interval }) as unknown as Trigger)
  const [actions, setActions] = useState<RoutineAction[]>([])
  const [preCondition, setPreCondition] = useState<PreCondition | null>(null)

  /**
   * Handle trigger change
   */
  const handleTriggerChange = useCallback((newTrigger: Trigger) => {
    setTrigger(newTrigger)
  }, [])

  /**
   * Handle actions change
   */
  const handleActionsChange = useCallback((newActions: RoutineAction[]) => {
    setActions(newActions)
  }, [])

  /**
   * Handle pre-condition change
   */
  const handlePreConditionChange = useCallback((newPreCondition: PreCondition | null) => {
    setPreCondition(newPreCondition)
  }, [])

  /**
   * Handle save button click
   */
  const handleSave = useCallback(() => {
    // Validate trigger has required type
    if (!trigger?.trigger_type) {
      toast.error('Please select a trigger type')
      return
    }

    // Validate trigger configuration is complete
    const validationError = validateTriggerWithSchema(trigger)
    if (validationError) {
      toast.error(validationError)
      return
    }

    const routine: Routine = {
      routine_id: generateUUID(),
      name: '', // Will be auto-generated by generateRoutineName
      trigger,
      actions,
      pre_condition: preCondition,
    }
    onComplete(routine)
  }, [trigger, actions, preCondition, onComplete])

  /**
   * Handle cancel button click
   */
  const handleCancel = useCallback(() => {
    onCancel()
  }, [onCancel])

  // Check if save is enabled (at least one action required)
  const canSave = actions.length > 0

  return (
    <div
      className="border border-gray-700 dark:border-gray-600 rounded"
      data-testid="new-routine-card"
    >
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 bg-gray-800/30 dark:bg-gray-700/30">
        <span className="text-sm font-medium text-white dark:text-gray-100">
          New Routine
        </span>
      </div>

      {/* Body - Always expanded */}
      <div className="px-4 pb-4 pt-2 border-t border-gray-800 dark:border-gray-700 space-y-4">
        {/* Trigger Selector */}
        <div>
          <label className="block text-xs text-gray-500 dark:text-gray-400 mb-2">
            Trigger
          </label>
          <TriggerForm
            value={trigger}
            onChange={handleTriggerChange}
            disabled={disabled}
            compact
          />
          <PreConditionForm
            preCondition={preCondition as any}  // eslint-disable-line @typescript-eslint/no-explicit-any
            onChange={handlePreConditionChange as any}  // eslint-disable-line @typescript-eslint/no-explicit-any
            routineIndex={0}
            disabled={disabled}
          />
        </div>

        {/* Action List */}
        <div>
          <label className="block text-xs text-gray-500 dark:text-gray-400 mb-2">
            Actions
          </label>
          <ActionList
            actions={actions}
            onActionsChange={handleActionsChange}
            disabled={disabled}
            useSecondsTiming={useSecondsTiming}
          />
          {actions.length === 0 && (
            <p className="mt-2 text-xs text-gray-500 dark:text-gray-400 italic">
              Add at least one action to save the routine
            </p>
          )}
        </div>

        {/* Buttons */}
        <div className="flex justify-end gap-2 pt-2">
          <button
            type="button"
            onClick={handleCancel}
            disabled={disabled}
            data-testid="cancel-new-routine"
            className="px-4 py-2 text-sm text-gray-400 dark:text-gray-500 hover:text-white dark:hover:text-gray-300 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSave}
            disabled={disabled || !canSave}
            className="px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            data-testid="save-routine"
          >
            Add Routine
          </button>
        </div>
      </div>
    </div>
  )
}

export default memo(NewRoutineCard)
