/**
 * NewRoutineCard - Inline wizard for creating new routines
 *
 * Per unified-scheduler-mockup.html, displays an expanded card with:
 * - TriggerSelector for type and configuration
 * - ActionList for adding actions
 * - Save/Cancel buttons
 *
 * @module components/scheduler/ScheduleEditor/NewRoutineCard
 */

import { useState, useCallback, memo } from 'react'
import PropTypes from 'prop-types'
import toast from 'react-hot-toast'
import TriggerSelector from '../TriggerSelector'
import ActionList from '../RoutineEditor/ActionList'
import { createDefaultTrigger, validateTrigger } from '../TriggerSelector/constants'
import { generateUUID } from '@/utils/uuid'

/**
 * NewRoutineCard component
 *
 * @param {Object} props - Component props
 * @param {Function} props.onComplete - Callback when routine is saved
 * @param {Function} props.onCancel - Callback when creation is cancelled
 * @param {boolean} [props.disabled=false] - Whether form is disabled
 * @returns {JSX.Element} New routine card component
 *
 * @example
 * <NewRoutineCard
 *   onComplete={(routine) => console.log('created', routine)}
 *   onCancel={() => console.log('cancelled')}
 * />
 */
function NewRoutineCard({ onComplete, onCancel, disabled = false, useSecondsTiming = false }) {
  // Initialize with default interval trigger
  const [trigger, setTrigger] = useState(() => createDefaultTrigger('interval'))
  const [actions, setActions] = useState([])

  /**
   * Handle trigger change
   */
  const handleTriggerChange = useCallback((newTrigger) => {
    setTrigger(newTrigger)
  }, [])

  /**
   * Handle actions change
   */
  const handleActionsChange = useCallback((newActions) => {
    setActions(newActions)
  }, [])

  /**
   * Handle save button click
   */
  const handleSave = useCallback(() => {
    // Validate trigger has required type
    if (!trigger?.trigger_type) {
      toast.error('Please select a trigger type')
      return
    }

    // Validate trigger configuration is complete
    const validationError = validateTrigger(trigger)
    if (validationError) {
      toast.error(validationError)
      return
    }

    const routine = {
      routine_id: generateUUID(),
      name: '', // Will be auto-generated by generateRoutineName
      trigger,
      actions,
    }
    onComplete(routine)
  }, [trigger, actions, onComplete])

  /**
   * Handle cancel button click
   */
  const handleCancel = useCallback(() => {
    onCancel()
  }, [onCancel])

  // Check if save is enabled (at least one action required)
  const canSave = actions.length > 0

  return (
    <div
      className="border border-gray-700 dark:border-gray-600 rounded"
      data-testid="new-routine-card"
    >
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 bg-gray-800/30 dark:bg-gray-700/30">
        <span className="text-sm font-medium text-white dark:text-gray-100">
          New Routine
        </span>
      </div>

      {/* Body - Always expanded */}
      <div className="px-4 pb-4 pt-2 border-t border-gray-800 dark:border-gray-700 space-y-4">
        {/* Trigger Selector */}
        <div>
          <label className="block text-xs text-gray-500 dark:text-gray-400 mb-2">
            Trigger
          </label>
          <TriggerSelector
            trigger={trigger}
            onChange={handleTriggerChange}
            disabled={disabled}
          />
        </div>

        {/* Action List */}
        <div>
          <label className="block text-xs text-gray-500 dark:text-gray-400 mb-2">
            Actions
          </label>
          <ActionList
            actions={actions}
            onActionsChange={handleActionsChange}
            disabled={disabled}
            useSecondsTiming={useSecondsTiming}
          />
          {actions.length === 0 && (
            <p className="mt-2 text-xs text-gray-500 dark:text-gray-400 italic">
              Add at least one action to save the routine
            </p>
          )}
        </div>

        {/* Buttons */}
        <div className="flex justify-end gap-2 pt-2">
          <button
            type="button"
            onClick={handleCancel}
            disabled={disabled}
            className="px-4 py-2 text-sm text-gray-400 dark:text-gray-500 hover:text-white dark:hover:text-gray-300 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSave}
            disabled={disabled || !canSave}
            className="px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            data-testid="save-routine"
          >
            Add Routine
          </button>
        </div>
      </div>
    </div>
  )
}

NewRoutineCard.propTypes = {
  /** Callback when routine is saved */
  onComplete: PropTypes.func.isRequired,
  /** Callback when creation is cancelled */
  onCancel: PropTypes.func.isRequired,
  /** Whether form is disabled */
  disabled: PropTypes.bool,
  /** Whether to show explicit seconds timing vs auto-stagger */
  useSecondsTiming: PropTypes.bool,
}

export default memo(NewRoutineCard)
